language: java
jdk: oraclejdk8
sudo: false

cache:
  directories:
  - "$HOME/.m2"

before_install:
- gem install dpl --source http://rubygems.org
- openssl aes-256-cbc -K $encrypted_2a4430333cb6_key -iv $encrypted_2a4430333cb6_iv -in travis/deploy_rsa.enc -out /tmp/deploy_rsa -d

addons:
  ssh_known_hosts:
  - cognosis2.mit.edu

install: true

script:
- mvn package

deploy:
- provider: script
  skip_cleanup: true
  script: travis/deploy.sh
  on:
    all_branches: true

notifications:
  slack:
    rooms:
    - secure: Z3A5wv/NkuCBJ9u31QYJwHV1QUKa5qltnJ8NK/Gz6bkFg3hokNFK3oQruc9K1Mx2ozNTWOp3KS+3XIHrdq0blIUuMnogPm+YahAntSXLw7SzBbd1YIqZ/JuaHd5XZTeXda+GBQQfBd4fym8rg460j/HJbTmI0b+JxdWUFRFF71abBoUCZW59NX9XZM5UEisUH6W+LfdmwfYgJCqpFtHK6ejEUfsLbUQxqb9BkVxwV5Xb62O/unJeqJLDVTiEXNsNPQWnINgduzF5LlVTBO7wbFTV6z78b+kfWSzYumt/vgOedrTsVY8wzSbWCzK3AhvMUii9MPGg8ZSkEzBuRpZAFdJF30f8qz/Eu3xwRmZMz5BjUo84LE4XLCv5kZMuHEDo7QgJ+1DTdzo+ZsCcQH0xBXdjlDI+oAbNlstS3DsgzO8YNuVR/VF5BwcwEY2i9vD5IYjIhvakOsatkeo2IGfwP1cs3yuAIJl+Q0rAb79vaAfyqBiE3T5jFYT+ZI8FMDFM/hYzgTArQ1G3zQSUz1f+4n4OkvrtBBQkgIuVO22E1n07OnO+9yZoCRHM65VQI+nlyWybjRynbAg0q4OhDEBcX7lmiZXIWpAsfnd9OTwtznHZz1PsR3jkelFmGStE7Ovw49VtUeR+qDP05gTX74vnujRJ6+uuBoB0YtYHYeQ6uzI=
    on_success: change
    on_failure: always
